from django.test import TestCase

# Create your tests here.
from bmrs.test.test_all_decorators_test_case import TestAllDecoratorsTestCase
from bmrs.test.test_service_bmrs_build_url_test_case import TestServiceBmrsBuildUrlTestCase
from bmrs.test.test_service_bmrs_date_retriever_test_case import TestServiceBmrsDateRetrieverTestCase